# -*- coding: utf-8 -*-
"""Gradient Boosting Regressor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WXOK-_b97aKqS3tVvCfJynz3lvZzvOYp
"""

from sklearn.ensemble import GradientBoostingRegressor

# Entrenamiento del modelo Gradient Boosting
gb_regressor = GradientBoostingRegressor()
gb_regressor.fit(X_train_imputed, y_train)

# Predicción
y_predict_gb_imputed = gb_regressor.predict(X_test_imputed)

# Evaluación del modelo
mse_gb_imputed = mean_squared_error(y_test, y_predict_gb_imputed)
r2_gb_imputed = gb_regressor.score(X_test_imputed, y_test)
print("Gradient Boosting Mean Squared Error (with imputation):", mse_gb_imputed)
print("Gradient Boosting R^2 Score (with imputation):", r2_gb_imputed)