# -*- coding: utf-8 -*-
"""Modelos con scikit-learn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VwD__hH2kvh1gqv7j3BdT9MfQTtC0HRE
"""

#Support Vector Regressor (SVR)
from sklearn.svm import SVR

# Entrenamiento del modelo SVR
svr_regressor = SVR()
svr_regressor.fit(X_train_imputed, y_train)

# Predicción
y_predict_svr_imputed = svr_regressor.predict(X_test_imputed)

# Evaluación del modelo
mse_svr_imputed = mean_squared_error(y_test, y_predict_svr_imputed)
r2_svr_imputed = svr_regressor.score(X_test_imputed, y_test)
print("SVR Mean Squared Error (with imputation):", mse_svr_imputed)
print("SVR R^2 Score (with imputation):", r2_svr_imputed)